name: Send a HTTP Request when new RSS item is detected
on:
  rss:
    url: 
#      - https://hidadeng.github.io/index.xml
#      - https://discuss-cn.bestxtools.com/atom/t/weekly/discussions
#      - https://feeds.feedburner.com/ruanyifeng
#      - http://blog.farmostwood.net/feed
      - http://fz0512.com/feed
jobs:
  request:
    name: Request
    runs-on: ubuntu-latest
    steps:
      - name: Make a HTTP Request      
        uses: actionsflow/axios@main
        with:
          url: https://cubox.pro/c/api/save/enlj2f8qjcex3u
          method: POST
          body: |
            {
              "link":"${{on.rss.outputs.link}}", 
              "title": "${{on.rss.outputs.title}}",
              "content":"<<<${{on.rss.outputs.contentSnippet}}>>>",
              "folder":"收集箱"
            }
